[package]
name = "authfilter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.1.4"
log = "0.4.14"

[lib]
crate-type = ["cdylib", "lib"]
