apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpdump
  name: httpdump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpdump
  template:
    metadata:
      labels:
        app: httpdump
    spec:
      containers:
      - image: sinofool/httpdump
        imagePullPolicy: Always
        name: httpdump
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: httpdump
spec:
  type: NodePort
  selector:
    app: httpdump 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpdump-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpdump
spec:
  hosts:
  - "*"
  gateways:
  - httpdump-gateway
  http:
  - route:
    - destination:
        host: httpdump
        port:
          number: 8080
